# -*- coding: utf-8 -*-
"""Núcleo_Familiar_Parcial_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10I6BI3Dicm34YltSq6Fu85XP6FJDKoae
"""

class Persona:
    def __init__(self, nombre, genero):
        self.nombre = nombre
        self.genero = genero
        self.hijos = []

    def agregar_hijo(self, hijo):
        self.hijos.append(hijo)

    def es_padre(self, hijo):
        return self.genero == "hombre" and hijo in self.hijos

    def es_madre(self, hijo):
        return self.genero == "mujer" and hijo in self.hijos

class Familia:
    def __init__(self):
        self.personas = {}

    def agregar_persona(self, persona):
        self.personas[persona.nombre] = persona

    def obtener_padre(self, nombre_hijo):
        for persona in self.personas.values():
            if persona.es_padre(nombre_hijo):
                return persona.nombre
        return None

    def obtener_madre(self, nombre_hijo):
        for persona in self.personas.values():
            if persona.es_madre(nombre_hijo):
                return persona.nombre
        return None

# Ejemplo de uso
familia = Familia()

juan = Persona("Juan", "hombre")
ana = Persona("Ana", "mujer")

juan.agregar_hijo("Ana")
familia.agregar_persona(juan)
familia.agregar_persona(ana)

print(familia.obtener_padre("Ana"))  # Salida: Juan
print(familia.obtener_madre("Ana"))  # Salida: None

# Continuando con la familia anterior
maria = Persona("María", "mujer")
juan.agregar_hijo("María")
familia.agregar_persona(maria)

print(familia.obtener_padre("María"))  # Salida: Juan
print(familia.obtener_madre("María"))  # Salida: None

# Crear una nueva familia
familia2 = Familia()

pedro = Persona("Pedro", "hombre")
luisa = Persona("Luisa", "mujer")
sofia = Persona("Sofía", "mujer")

pedro.agregar_hijo("Sofía")
luisa.agregar_hijo("Sofía")  # Aunque en este ejemplo no se diferencia entre padre y madre, se agrega para ilustrar

familia2.agregar_persona(pedro)
familia2.agregar_persona(luisa)
familia2.agregar_persona(sofia)

print(familia2.obtener_padre("Sofía"))  # Salida: Pedro
print(familia2.obtener_madre("Sofía"))  # Salida: Luisa

# Preguntar si una persona es padre o madre de varios hijos
print(juan.hijos)  # Salida: ['Ana', 'María']

# Preguntar por todos los hijos de una persona
for persona in familia.personas.values():
    if persona.hijos:
        print(f"{persona.nombre} tiene los siguientes hijos: {persona.hijos}")

# Agregar más hijos a Juan
juan.agregar_hijo("Carlos")
familia.agregar_persona(Persona("Carlos", "hombre"))  # Agregar a Carlos a la familia

print(juan.hijos)  # Salida: ['Ana', 'María', 'Carlos']

